### PR TITLE
Updated to 1.9

### PR DESCRIPTION
**Pull request by TheFluffyWalrus**
Changed the sounds Names to the proper 1.9 ones also added a temporary download place while we wait for you to upload to bukkit Was unable to figure out what the FIZZ sound was so i replaced it with the anvil place sound and works out pretty good.

### CODE REVIEW

**Comment by Battelman2** [comment]
Thank you for helping us transition to 1.9. We are actively preparing a 1.9 release and this will certainly be included.

**Comment by TheFluffyWalrus** [comment]
right now i am working on implementing monster eggs into the build flag so they can not be placed

**Comment by Battelman2** [comment]
Perfect. Something else we have to look at yet is the new door types, possibly including the new trap door mechanics.

**Comment by Battelman2** [comment]
We will merge this as soon as we finish our localization changes on our branch.

**Comment by TheFluffyWalrus** [comment]
do you have teamspeak? if so join me at ts.fluffcraft.com better than talking here

**Comment by Battelman2** [comment]
Please create a new pull request when we finish our localization changes. I will contact you will details, but I am closing this as it will not properly function with our internal branch changes.

**Pull request closed without merging**
